/**
 * Fluent IR namespace for the go grammar.
 *
 * Generated by ir-codegen from the go grammar.
 * Do not edit manually — re-run ir-codegen to regenerate.
 *
 * Usage:
 *   ir.fn('main').body('fmt.Println("hello")').render()
 *   ir.type_('Point struct {\n\tX float64\n\tY float64\n}').render()
 *   ir.import_('"fmt"').render()
 *   ir.if_('err != nil').then('return err').render()
 */

import { fn } from './nodes/function.ts';
import { type_ } from './nodes/type-declaration.ts';
import { import_ } from './nodes/import.ts';
import { if_ } from './nodes/if.ts';

export const ir = {
	fn,
	type: type_,
	import: import_,
	if: if_,
};
