/**
 * Go IR — typed builders, renderer, and validation.
 *
 * Generated by ir-codegen from the go grammar.
 * Do not edit manually — re-run ir-codegen to regenerate.
 */

export type {
	GoGrammar,
	FunctionDeclaration,
	FunctionDeclarationConfig,
	MethodDeclaration,
	MethodDeclarationConfig,
	TypeDeclaration,
	TypeDeclarationConfig,
	ImportDeclaration,
	ImportDeclarationConfig,
	IfStatement,
	IfStatementConfig,
	SourceFile,
	SourceFileConfig,
	GoIrNode,
	ValidationResult,
} from './types.ts';

export { render, renderSilent, validateFast, assertValid } from './render.ts';

export { functionDeclaration } from './nodes/function.ts';
export { typeDeclaration } from './nodes/type-declaration.ts';
export { importDeclaration } from './nodes/import.ts';
export { ifStatement } from './nodes/if.ts';

export { ir } from './fluent.ts';
