/**
 * Render Go IR nodes to source strings.
 *
 * Generated by ir-codegen from the go grammar.
 * Render cases are scaffolded — fill in language-specific formatting.
 */

import type { GoIrNode } from './types.ts';
import type { ValidationResult } from '@refactory/grammar-types';

function indent(text: string): string {
	return text
		.split('\n')
		.map((line) => '\t' + line)
		.join('\n');
}

export function renderSilent(node: GoIrNode): string {
	switch (node.kind) {
		case 'function_declaration': {
			const ret = node.returnType ? ` ${node.returnType}` : '';
			const params = node.parameters ?? '';
			return `func ${node.name}(${params})${ret} {\n${indent(String(node.body))}\n}`;
		}
		case 'type_declaration':
			return `type ${String(node.children)}`;
		case 'import_declaration':
			return `import ${String(node.children)}`;
		case 'if_statement': {
			const init = node.initializer ? `${node.initializer}; ` : '';
			let out = `if ${init}${node.condition} {\n${indent(String(node.consequence))}\n}`;
			if (node.alternative) {
				out += ` else {\n${indent(String(node.alternative))}\n}`;
			}
			return out;
		}
		case 'source_file':
			return (node.children as unknown[]).map((c) =>
				typeof c === 'string' ? c : renderSilent(c as GoIrNode)
			).join('\n\n');
		default:
			throw new Error(`render: unknown node kind: ${(node as { kind: string }).kind}`);
	}
}

export function render(node: GoIrNode): string {
	return assertValid(renderSilent(node));
}

// Lightweight regex-based validation
function detectErrors(source: string): Array<{ offset: number; kind: 'ERROR' }> {
	const errors: Array<{ offset: number; kind: 'ERROR' }> = [];
	const open = (source.match(/{/g) ?? []).length;
	const close = (source.match(/}/g) ?? []).length;
	if (open !== close) {
		errors.push({ offset: source.lastIndexOf(open > close ? '{' : '}'), kind: 'ERROR' });
	}
	return errors;
}

export function validateFast(source: string): ValidationResult {
	const errors = detectErrors(source);
	return errors.length === 0 ? { ok: true } : { ok: false, errors };
}

export function assertValid(source: string): string {
	const result = validateFast(source);
	if (result.ok) return source;
	const details = result.errors.map((e) => `${e.kind}@${e.offset}`).join(', ');
	throw new Error(`Go validation failed: ${details}`);
}
