/**
 * Go IR node types.
 *
 * Generated by ir-codegen from the go grammar.
 * Do not edit manually — re-run ir-codegen to regenerate.
 */

import type { NodeType, BuilderConfig, ValidationResult } from '@refactory/grammar-types';
import type GoTypes from '@codemod.com/jssg-types/langs/go';

// Grammar primitives
export type GoGrammar = GoTypes;

// Node types — grammar-derived, zero hand-rolled fields
export type FunctionDeclaration = NodeType<GoGrammar, 'function_declaration'>;
export type MethodDeclaration = NodeType<GoGrammar, 'method_declaration'>;
export type TypeDeclaration = NodeType<GoGrammar, 'type_declaration'>;
export type ImportDeclaration = NodeType<GoGrammar, 'import_declaration'>;
export type IfStatement = NodeType<GoGrammar, 'if_statement'>;
export type SourceFile = NodeType<GoGrammar, 'source_file'>;

// Builder configs
export type FunctionDeclarationConfig = BuilderConfig<GoGrammar, FunctionDeclaration>;
export type MethodDeclarationConfig = BuilderConfig<GoGrammar, MethodDeclaration>;
export type TypeDeclarationConfig = BuilderConfig<GoGrammar, TypeDeclaration>;
export type ImportDeclarationConfig = BuilderConfig<GoGrammar, ImportDeclaration>;
export type IfStatementConfig = BuilderConfig<GoGrammar, IfStatement>;
export type SourceFileConfig = BuilderConfig<GoGrammar, SourceFile>;

// Discriminated union
export type GoIrNode =
	| FunctionDeclaration
	| MethodDeclaration
	| TypeDeclaration
	| ImportDeclaration
	| IfStatement
	| SourceFile;

export type { ValidationResult };
