/**
 * Emits a fluent namespace module that maps short names to builder constructors.
 */

import { toShortName, toFileName, toGrammarTypeName } from '../naming.ts';

export interface EmitFluentConfig {
  grammar: string;
  nodeKinds: string[];
}

export function emitFluent(config: EmitFluentConfig): string {
  const { grammar, nodeKinds } = config;
  const grammarTypeName = toGrammarTypeName(grammar);
  const grammarPrefix = grammarTypeName.slice(0, -5);

  const imports: string[] = [];
  const entries: string[] = [];

  for (const kind of nodeKinds) {
    const shortName = toShortName(kind);
    const fileName = toFileName(kind);

    imports.push(`import { ${shortName} } from './nodes/${fileName}.ts';`);

    // If the short name contains a trailing underscore (reserved word escape),
    // use the base word (without underscore) as the property key
    const baseName = shortName.endsWith('_') ? shortName.slice(0, -1) : shortName;
    if (baseName !== shortName) {
      entries.push(`  ${baseName}: ${shortName},`);
    } else {
      entries.push(`  ${shortName},`);
    }
  }

  const lines: string[] = [
    '// Auto-generated by ir-codegen — do not edit',
    '',
    ...imports,
    '',
    `export const ir = {`,
    ...entries,
    `} as const;`,
    '',
    `export type ${grammarPrefix}Ir = typeof ir;`,
    '',
  ];

  return lines.join('\n');
}
