/**
 * Emits an index.ts barrel file that re-exports all generated modules.
 */

import { toFactoryName, toGrammarTypeName } from '../naming.ts';

export interface EmitIndexConfig {
  grammar: string;
  nodeKinds: string[];
}

export function emitIndex(config: EmitIndexConfig): string {
  const { grammar, nodeKinds } = config;

  const factoryNames = nodeKinds.map((kind) => toFactoryName(kind));

  const lines: string[] = [
    '// Auto-generated by ir-codegen — do not edit',
    '',
    `export * from './types.ts';`,
    `export * from './render.ts';`,
    `export * from './validate-fast.ts';`,
    `export { ir, ${factoryNames.join(', ')} } from './fluent.ts';`,
    '',
  ];

  return lines.join('\n');
}
