/**
 * Builder for `class_declaration`.
 *
 * Generated by ir-codegen from the typescript grammar.
 * Do not edit manually — re-run ir-codegen to regenerate.
 */

import type { BuilderTerminal } from '@refactory/grammar-types';
import type { ClassDeclaration, ClassDeclarationConfig } from '../types.ts';
import { renderSilent, assertValid } from '../render.ts';

export function classDeclaration(config: ClassDeclarationConfig): ClassDeclaration {
	return {
		kind: 'class_declaration' as const,
		name: config.name,
		body: config.body,
		typeParameters: config.typeParameters,
	} as ClassDeclaration;
}

class ClassBuilder implements BuilderTerminal<ClassDeclaration> {
	private _name: string;
	private _body?: string;
	private _extends?: string;
	private _implements?: string[];
	private _typeParams?: string;

	constructor(name: string) {
		this._name = name;
	}

	extends_(base: string): this {
		this._extends = base;
		return this;
	}

	implements_(...interfaces: string[]): this {
		this._implements = interfaces;
		return this;
	}

	generic(typeParams: string): this {
		this._typeParams = typeParams;
		return this;
	}

	body(body: string): this {
		this._body = body;
		return this;
	}

	build(): ClassDeclaration {
		return classDeclaration({
			name: this._name,
			body: this._body,
			typeParameters: this._typeParams,
		} as ClassDeclarationConfig);
	}

	render(): string {
		return assertValid(renderSilent(this.build()));
	}

	renderSilent(): string {
		return renderSilent(this.build());
	}
}

export function class_(name: string): ClassBuilder {
	return new ClassBuilder(name);
}
