/**
 * Builder for `import_statement`.
 *
 * Generated by ir-codegen from the typescript grammar.
 * Do not edit manually — re-run ir-codegen to regenerate.
 */

import type { BuilderTerminal } from '@refactory/grammar-types';
import type { ImportStatement, ImportStatementConfig } from '../types.ts';
import { renderSilent, assertValid } from '../render.ts';

export function importStatement(config: ImportStatementConfig): ImportStatement {
	return {
		kind: 'import_statement' as const,
		source: config.source,
	} as ImportStatement;
}

class ImportBuilder implements BuilderTerminal<ImportStatement> {
	private _source: string;
	private _names?: string[];
	private _default?: string;
	private _namespace?: string;

	constructor(source: string) {
		this._source = source;
	}

	named(...names: string[]): this {
		this._names = names;
		return this;
	}

	default_(name: string): this {
		this._default = name;
		return this;
	}

	namespace(name: string): this {
		this._namespace = name;
		return this;
	}

	build(): ImportStatement {
		return importStatement({
			source: this._source,
		} as ImportStatementConfig);
	}

	render(): string {
		return assertValid(renderSilent(this.build()));
	}

	renderSilent(): string {
		return renderSilent(this.build());
	}
}

export function import_(source: string): ImportBuilder {
	return new ImportBuilder(source);
}
