/**
 * Builder for `interface_declaration`.
 *
 * Generated by ir-codegen from the typescript grammar.
 * Do not edit manually — re-run ir-codegen to regenerate.
 */

import type { BuilderTerminal } from '@refactory/grammar-types';
import type { InterfaceDeclaration, InterfaceDeclarationConfig } from '../types.ts';
import { renderSilent, assertValid } from '../render.ts';

export function interfaceDeclaration(config: InterfaceDeclarationConfig): InterfaceDeclaration {
	return {
		kind: 'interface_declaration' as const,
		name: config.name,
		body: config.body,
		typeParameters: config.typeParameters,
	} as InterfaceDeclaration;
}

class InterfaceBuilder implements BuilderTerminal<InterfaceDeclaration> {
	private _name: string;
	private _body?: string;
	private _extends?: string[];
	private _typeParams?: string;

	constructor(name: string) {
		this._name = name;
	}

	extends_(...bases: string[]): this {
		this._extends = bases;
		return this;
	}

	generic(typeParams: string): this {
		this._typeParams = typeParams;
		return this;
	}

	body(body: string): this {
		this._body = body;
		return this;
	}

	build(): InterfaceDeclaration {
		return interfaceDeclaration({
			name: this._name,
			body: this._body,
			typeParameters: this._typeParams,
		} as InterfaceDeclarationConfig);
	}

	render(): string {
		return assertValid(renderSilent(this.build()));
	}

	renderSilent(): string {
		return renderSilent(this.build());
	}
}

export function interface_(name: string): InterfaceBuilder {
	return new InterfaceBuilder(name);
}
