/**
 * Builder for `type_alias_declaration`.
 *
 * Generated by ir-codegen from the typescript grammar.
 * Do not edit manually — re-run ir-codegen to regenerate.
 */

import type { BuilderTerminal } from '@refactory/grammar-types';
import type { TypeAliasDeclaration, TypeAliasDeclarationConfig } from '../types.ts';
import { renderSilent, assertValid } from '../render.ts';

export function typeAliasDeclaration(config: TypeAliasDeclarationConfig): TypeAliasDeclaration {
	return {
		kind: 'type_alias_declaration' as const,
		name: config.name,
		value: config.value,
		typeParameters: config.typeParameters,
	} as TypeAliasDeclaration;
}

class TypeAliasBuilder implements BuilderTerminal<TypeAliasDeclaration> {
	private _name: string;
	private _value: string;
	private _typeParams?: string;

	constructor(name: string, value: string) {
		this._name = name;
		this._value = value;
	}

	generic(typeParams: string): this {
		this._typeParams = typeParams;
		return this;
	}

	build(): TypeAliasDeclaration {
		return typeAliasDeclaration({
			name: this._name,
			value: this._value,
			typeParameters: this._typeParams,
		} as TypeAliasDeclarationConfig);
	}

	render(): string {
		return assertValid(renderSilent(this.build()));
	}

	renderSilent(): string {
		return renderSilent(this.build());
	}
}

export function type_(name: string, value: string): TypeAliasBuilder {
	return new TypeAliasBuilder(name, value);
}
