/**
 * Fluent IR namespace for the typescript grammar.
 *
 * Generated by ir-codegen from the typescript grammar.
 * Do not edit manually — re-run ir-codegen to regenerate.
 *
 * Usage:
 *   ir.fn('greet').params('name: string').returns('string').body('return `Hello, ${name}`').render()
 *   ir.class_('Point').extends_('Base').body('x = 0;\ny = 0;').render()
 *   ir.interface_('Shape').body('area(): number;').render()
 *   ir.type_('ID', 'string | number').render()
 *   ir.import_("'./utils'").named('foo', 'bar').render()
 */

import { fn } from './nodes/function.ts';
import { class_ } from './nodes/class.ts';
import { interface_ } from './nodes/interface.ts';
import { type_ } from './nodes/type-alias.ts';
import { import_ } from './nodes/import.ts';

export const ir = {
	fn,
	class: class_,
	interface: interface_,
	type: type_,
	import: import_,
};
