/**
 * TypeScript IR — typed builders, renderer, and validation.
 *
 * Generated by ir-codegen from the typescript grammar.
 * Do not edit manually — re-run ir-codegen to regenerate.
 */

export type {
	TSGrammar,
	FunctionDeclaration,
	FunctionDeclarationConfig,
	ClassDeclaration,
	ClassDeclarationConfig,
	InterfaceDeclaration,
	InterfaceDeclarationConfig,
	TypeAliasDeclaration,
	TypeAliasDeclarationConfig,
	ImportStatement,
	ImportStatementConfig,
	ExportStatement,
	ExportStatementConfig,
	IfStatement,
	IfStatementConfig,
	Program,
	ProgramConfig,
	TSIrNode,
	ValidationResult,
} from './types.ts';

export { render, renderSilent, validateFast, assertValid } from './render.ts';

export { functionDeclaration } from './nodes/function.ts';
export { classDeclaration } from './nodes/class.ts';
export { interfaceDeclaration } from './nodes/interface.ts';
export { typeAliasDeclaration } from './nodes/type-alias.ts';
export { importStatement } from './nodes/import.ts';

export { ir } from './fluent.ts';
