/**
 * Render TypeScript IR nodes to source strings.
 *
 * Generated by ir-codegen from the typescript grammar.
 * Render cases are scaffolded — fill in language-specific formatting.
 */

import type { TSIrNode } from './types.ts';
import type { ValidationResult } from '@refactory/grammar-types';

function indent(text: string): string {
	return text
		.split('\n')
		.map((line) => '  ' + line)
		.join('\n');
}

export function renderSilent(node: TSIrNode): string {
	switch (node.kind) {
		case 'function_declaration': {
			const tp = node.typeParameters ? `<${node.typeParameters}>` : '';
			const params = node.parameters ?? '';
			const ret = node.returnType ? `: ${node.returnType}` : '';
			return `function ${node.name}${tp}(${params})${ret} {\n${indent(String(node.body))}\n}`;
		}
		case 'class_declaration': {
			const tp = node.typeParameters ? `<${node.typeParameters}>` : '';
			const body = node.body ? `\n${indent(String(node.body))}\n` : '\n';
			return `class ${node.name}${tp} {${body}}`;
		}
		case 'interface_declaration': {
			const tp = node.typeParameters ? `<${node.typeParameters}>` : '';
			const body = node.body ? `\n${indent(String(node.body))}\n` : '\n';
			return `interface ${node.name}${tp} {${body}}`;
		}
		case 'type_alias_declaration': {
			const tp = node.typeParameters ? `<${node.typeParameters}>` : '';
			return `type ${node.name}${tp} = ${node.value};`;
		}
		case 'import_statement':
			return `import ${node.source};`;
		case 'export_statement':
			return `export ${node.declaration ? String(node.declaration) : ''};`;
		case 'if_statement': {
			let out = `if (${node.condition}) {\n${indent(String(node.consequence))}\n}`;
			if (node.alternative) {
				out += ` else {\n${indent(String(node.alternative))}\n}`;
			}
			return out;
		}
		case 'program':
			return (node.children as unknown[]).map((c) =>
				typeof c === 'string' ? c : renderSilent(c as TSIrNode)
			).join('\n\n');
		default:
			throw new Error(`render: unknown node kind: ${(node as { kind: string }).kind}`);
	}
}

export function render(node: TSIrNode): string {
	return assertValid(renderSilent(node));
}

// Lightweight regex-based validation
function detectErrors(source: string): Array<{ offset: number; kind: 'ERROR' }> {
	const errors: Array<{ offset: number; kind: 'ERROR' }> = [];
	const open = (source.match(/{/g) ?? []).length;
	const close = (source.match(/}/g) ?? []).length;
	if (open !== close) {
		errors.push({ offset: source.lastIndexOf(open > close ? '{' : '}'), kind: 'ERROR' });
	}
	return errors;
}

export function validateFast(source: string): ValidationResult {
	const errors = detectErrors(source);
	return errors.length === 0 ? { ok: true } : { ok: false, errors };
}

export function assertValid(source: string): string {
	const result = validateFast(source);
	if (result.ok) return source;
	const details = result.errors.map((e) => `${e.kind}@${e.offset}`).join(', ');
	throw new Error(`TypeScript validation failed: ${details}`);
}
