/**
 * TypeScript IR node types.
 *
 * Generated by ir-codegen from the typescript grammar.
 * Do not edit manually — re-run ir-codegen to regenerate.
 */

import type { NodeType, BuilderConfig, ValidationResult } from '@refactory/grammar-types';
import type TSTypes from '@codemod.com/jssg-types/langs/typescript';

// Grammar primitives
export type TSGrammar = TSTypes;

// Node types — grammar-derived, zero hand-rolled fields
export type FunctionDeclaration = NodeType<TSGrammar, 'function_declaration'>;
export type ClassDeclaration = NodeType<TSGrammar, 'class_declaration'>;
export type InterfaceDeclaration = NodeType<TSGrammar, 'interface_declaration'>;
export type TypeAliasDeclaration = NodeType<TSGrammar, 'type_alias_declaration'>;
export type ImportStatement = NodeType<TSGrammar, 'import_statement'>;
export type ExportStatement = NodeType<TSGrammar, 'export_statement'>;
export type IfStatement = NodeType<TSGrammar, 'if_statement'>;
export type Program = NodeType<TSGrammar, 'program'>;

// Builder configs
export type FunctionDeclarationConfig = BuilderConfig<TSGrammar, FunctionDeclaration>;
export type ClassDeclarationConfig = BuilderConfig<TSGrammar, ClassDeclaration>;
export type InterfaceDeclarationConfig = BuilderConfig<TSGrammar, InterfaceDeclaration>;
export type TypeAliasDeclarationConfig = BuilderConfig<TSGrammar, TypeAliasDeclaration>;
export type ImportStatementConfig = BuilderConfig<TSGrammar, ImportStatement>;
export type ExportStatementConfig = BuilderConfig<TSGrammar, ExportStatement>;
export type IfStatementConfig = BuilderConfig<TSGrammar, IfStatement>;
export type ProgramConfig = BuilderConfig<TSGrammar, Program>;

// Discriminated union
export type TSIrNode =
	| FunctionDeclaration
	| ClassDeclaration
	| InterfaceDeclaration
	| TypeAliasDeclaration
	| ImportStatement
	| ExportStatement
	| IfStatement
	| Program;

export type { ValidationResult };
