// Auto-generated by ir-codegen — do not edit

import { abstract_type } from './nodes/abstract-type.ts';
import { arguments_ } from './nodes/arguments.ts';
import { array } from './nodes/array.ts';
import { array_type } from './nodes/array-type.ts';
import { assignment } from './nodes/assignment.ts';
import { associated_type } from './nodes/associated-type.ts';
import { async_block } from './nodes/async-block.ts';
import { attribute } from './nodes/attribute.ts';
import { attribute as attributeItem } from './nodes/attribute-item.ts';
import { await_ } from './nodes/await.ts';
import { base_field_initializer } from './nodes/base-field-initializer.ts';
import { binary } from './nodes/binary.ts';
import { block } from './nodes/block.ts';
import { block_comment } from './nodes/block-comment.ts';
import { bounded_type } from './nodes/bounded-type.ts';
import { bracketed_type } from './nodes/bracketed-type.ts';
import { break_ } from './nodes/break.ts';
import { call } from './nodes/call.ts';
import { captured_pattern } from './nodes/captured-pattern.ts';
import { closure } from './nodes/closure.ts';
import { closure_parameters } from './nodes/closure-parameters.ts';
import { compound_assignment_expr } from './nodes/compound-assignment-expr.ts';
import { const_block } from './nodes/const-block.ts';
import { const_ } from './nodes/const.ts';
import { const_parameter } from './nodes/const-parameter.ts';
import { constrained_type_parameter } from './nodes/constrained-type-parameter.ts';
import { continue_ } from './nodes/continue.ts';
import { declaration_list } from './nodes/declaration-list.ts';
import { dynamic_type } from './nodes/dynamic-type.ts';
import { else_clause } from './nodes/else-clause.ts';
import { enum_ } from './nodes/enum.ts';
import { enum_variant } from './nodes/enum-variant.ts';
import { enum_variant_list } from './nodes/enum-variant-list.ts';
import { expression } from './nodes/expression.ts';
import { extern_crate } from './nodes/extern-crate.ts';
import { extern_modifier } from './nodes/extern-modifier.ts';
import { field as fieldDeclaration } from './nodes/field-declaration.ts';
import { field_declaration_list } from './nodes/field-declaration-list.ts';
import { field as fieldExpression } from './nodes/field-expression.ts';
import { field_initializer } from './nodes/field-initializer.ts';
import { field_initializer_list } from './nodes/field-initializer-list.ts';
import { field_pattern } from './nodes/field-pattern.ts';
import { for_ } from './nodes/for.ts';
import { for_lifetimes } from './nodes/for-lifetimes.ts';
import { foreign_mod } from './nodes/foreign-mod.ts';
import { fn } from './nodes/function.ts';
import { function_modifiers } from './nodes/function-modifiers.ts';
import { function_signature } from './nodes/function-signature.ts';
import { function_type } from './nodes/function-type.ts';
import { generic_function } from './nodes/generic-function.ts';
import { generic_type } from './nodes/generic-type.ts';
import { generic_type_with_turbofish } from './nodes/generic-type-with-turbofish.ts';
import { higher_ranked_trait_bound } from './nodes/higher-ranked-trait-bound.ts';
import { if_ } from './nodes/if.ts';
import { impl } from './nodes/impl.ts';
import { index } from './nodes/index.ts';
import { inner_attribute } from './nodes/inner-attribute.ts';
import { label } from './nodes/label.ts';
import { let_chain } from './nodes/let-chain.ts';
import { let_condition } from './nodes/let-condition.ts';
import { let_ } from './nodes/let.ts';
import { lifetime } from './nodes/lifetime.ts';
import { line_comment } from './nodes/line-comment.ts';
import { loop } from './nodes/loop.ts';
import { macro_definition } from './nodes/macro-definition.ts';
import { macro_invocation } from './nodes/macro-invocation.ts';
import { macro_rule } from './nodes/macro-rule.ts';
import { match_arm } from './nodes/match-arm.ts';
import { match_block } from './nodes/match-block.ts';
import { match } from './nodes/match.ts';
import { match_pattern } from './nodes/match-pattern.ts';
import { mod } from './nodes/mod.ts';
import { mut_pattern } from './nodes/mut-pattern.ts';
import { negative_literal } from './nodes/negative-literal.ts';
import { optional_type_parameter } from './nodes/optional-type-parameter.ts';
import { or_pattern } from './nodes/or-pattern.ts';
import { ordered_field_declaration_list } from './nodes/ordered-field-declaration-list.ts';
import { parameter } from './nodes/parameter.ts';
import { parameters } from './nodes/parameters.ts';
import { parenthesized } from './nodes/parenthesized.ts';
import { pointer_type } from './nodes/pointer-type.ts';
import { qualified_type } from './nodes/qualified-type.ts';
import { range } from './nodes/range.ts';
import { range_pattern } from './nodes/range-pattern.ts';
import { raw_string_literal } from './nodes/raw-string-literal.ts';
import { ref_pattern } from './nodes/ref-pattern.ts';
import { reference } from './nodes/reference.ts';
import { reference_pattern } from './nodes/reference-pattern.ts';
import { reference_type } from './nodes/reference-type.ts';
import { removed_trait_bound } from './nodes/removed-trait-bound.ts';
import { return_ } from './nodes/return.ts';
import { scoped_identifier } from './nodes/scoped-identifier.ts';
import { scoped_type_identifier } from './nodes/scoped-type-identifier.ts';
import { scoped_use_list } from './nodes/scoped-use-list.ts';
import { self_parameter } from './nodes/self-parameter.ts';
import { shorthand_field_initializer } from './nodes/shorthand-field-initializer.ts';
import { slice_pattern } from './nodes/slice-pattern.ts';
import { file } from './nodes/source-file.ts';
import { static_ } from './nodes/static.ts';
import { string_literal } from './nodes/string-literal.ts';
import { struct_ as structExpression } from './nodes/struct-expression.ts';
import { struct_ as structItem } from './nodes/struct-item.ts';
import { struct_pattern } from './nodes/struct-pattern.ts';
import { token_binding_pattern } from './nodes/token-binding-pattern.ts';
import { token_repetition } from './nodes/token-repetition.ts';
import { token_repetition_pattern } from './nodes/token-repetition-pattern.ts';
import { token_tree } from './nodes/token-tree.ts';
import { token_tree_pattern } from './nodes/token-tree-pattern.ts';
import { trait_bounds } from './nodes/trait-bounds.ts';
import { trait } from './nodes/trait.ts';
import { try_block } from './nodes/try-block.ts';
import { try_ } from './nodes/try.ts';
import { tuple } from './nodes/tuple.ts';
import { tuple_pattern } from './nodes/tuple-pattern.ts';
import { tuple_struct_pattern } from './nodes/tuple-struct-pattern.ts';
import { tuple_type } from './nodes/tuple-type.ts';
import { type_arguments } from './nodes/type-arguments.ts';
import { type_binding } from './nodes/type-binding.ts';
import { type_cast } from './nodes/type-cast.ts';
import { type_ } from './nodes/type.ts';
import { type_parameters } from './nodes/type-parameters.ts';
import { unary } from './nodes/unary.ts';
import { union } from './nodes/union.ts';
import { unsafe_block } from './nodes/unsafe-block.ts';
import { use_as_clause } from './nodes/use-as-clause.ts';
import { use_ } from './nodes/use.ts';
import { use_list } from './nodes/use-list.ts';
import { use_wildcard } from './nodes/use-wildcard.ts';
import { variadic_parameter } from './nodes/variadic-parameter.ts';
import { visibility_modifier } from './nodes/visibility-modifier.ts';
import { where_clause } from './nodes/where-clause.ts';
import { where_predicate } from './nodes/where-predicate.ts';
import { while_ } from './nodes/while.ts';
import { yield_ } from './nodes/yield.ts';

export const ir = {
  abstract_type,
  arguments: arguments_,
  array,
  array_type,
  assignment,
  associated_type,
  async_block,
  attribute,
  attributeItem,
  await: await_,
  base_field_initializer,
  binary,
  block,
  block_comment,
  bounded_type,
  bracketed_type,
  break: break_,
  call,
  captured_pattern,
  closure,
  closure_parameters,
  compound_assignment_expr,
  const_block,
  const: const_,
  const_parameter,
  constrained_type_parameter,
  continue: continue_,
  declaration_list,
  dynamic_type,
  else_clause,
  enum: enum_,
  enum_variant,
  enum_variant_list,
  expression,
  extern_crate,
  extern_modifier,
  fieldDeclaration,
  field_declaration_list,
  fieldExpression,
  field_initializer,
  field_initializer_list,
  field_pattern,
  for: for_,
  for_lifetimes,
  foreign_mod,
  fn,
  function_modifiers,
  function_signature,
  function_type,
  generic_function,
  generic_type,
  generic_type_with_turbofish,
  higher_ranked_trait_bound,
  if: if_,
  impl,
  index,
  inner_attribute,
  label,
  let_chain,
  let_condition,
  let: let_,
  lifetime,
  line_comment,
  loop,
  macro_definition,
  macro_invocation,
  macro_rule,
  match_arm,
  match_block,
  match,
  match_pattern,
  mod,
  mut_pattern,
  negative_literal,
  optional_type_parameter,
  or_pattern,
  ordered_field_declaration_list,
  parameter,
  parameters,
  parenthesized,
  pointer_type,
  qualified_type,
  range,
  range_pattern,
  raw_string_literal,
  ref_pattern,
  reference,
  reference_pattern,
  reference_type,
  removed_trait_bound,
  return: return_,
  scoped_identifier,
  scoped_type_identifier,
  scoped_use_list,
  self_parameter,
  shorthand_field_initializer,
  slice_pattern,
  file,
  static: static_,
  string_literal,
  structExpression,
  structItem,
  struct_pattern,
  token_binding_pattern,
  token_repetition,
  token_repetition_pattern,
  token_tree,
  token_tree_pattern,
  trait_bounds,
  trait,
  try_block,
  try: try_,
  tuple,
  tuple_pattern,
  tuple_struct_pattern,
  tuple_type,
  type_arguments,
  type_binding,
  type_cast,
  type: type_,
  type_parameters,
  unary,
  union,
  unsafe_block,
  use_as_clause,
  use: use_,
  use_list,
  use_wildcard,
  variadic_parameter,
  visibility_modifier,
  where_clause,
  where_predicate,
  while: while_,
  yield: yield_,
} as const;

export type RustIr = typeof ir;
