/**
 * Builder for `function_declaration`.
 *
 * Generated by ir-codegen from the go grammar.
 * Do not edit manually — re-run ir-codegen to regenerate.
 */

import type { BuilderTerminal } from '@refactory/grammar-types';
import type { FunctionDeclaration, FunctionDeclarationConfig } from '../types.ts';
import { renderSilent, assertValid } from '../render.ts';

export function functionDeclaration(config: FunctionDeclarationConfig): FunctionDeclaration {
	return {
		kind: 'function_declaration' as const,
		name: config.name,
		parameters: config.parameters,
		body: config.body,
		returnType: config.returnType,
		typeParameters: config.typeParameters,
	} as FunctionDeclaration;
}

class FunctionBuilder implements BuilderTerminal<FunctionDeclaration> {
	private _name: string;
	private _params?: string;
	private _returnType?: string;
	private _body: string = '// todo';

	constructor(name: string) {
		this._name = name;
	}

	params(...params: string[]): this {
		this._params = params.join(', ');
		return this;
	}

	returns(type: string): this {
		this._returnType = type;
		return this;
	}

	body(body: string): this {
		this._body = body;
		return this;
	}

	build(): FunctionDeclaration {
		return functionDeclaration({
			name: this._name,
			parameters: this._params,
			returnType: this._returnType,
			body: this._body,
		} as FunctionDeclarationConfig);
	}

	render(): string {
		return assertValid(renderSilent(this.build()));
	}

	renderSilent(): string {
		return renderSilent(this.build());
	}
}

export function fn(name: string): FunctionBuilder {
	return new FunctionBuilder(name);
}
