/**
 * Builder for `if_statement`.
 *
 * Generated by ir-codegen from the go grammar.
 * Do not edit manually — re-run ir-codegen to regenerate.
 */

import type { BuilderTerminal } from '@refactory/grammar-types';
import type { IfStatement, IfStatementConfig, GoIrNode } from '../types.ts';
import { renderSilent, assertValid } from '../render.ts';

export function ifStatement(config: IfStatementConfig): IfStatement {
	return {
		kind: 'if_statement' as const,
		condition: config.condition,
		consequence: config.consequence,
		alternative: config.alternative,
		initializer: config.initializer,
	} as IfStatement;
}

class IfBuilder implements BuilderTerminal<IfStatement> {
	private _condition: string;
	private _consequence: string = '// todo';
	private _alternative?: string;
	private _initializer?: string;

	constructor(condition: string) {
		this._condition = condition;
	}

	init(stmt: string): this {
		this._initializer = stmt;
		return this;
	}

	then(body: string): this {
		this._consequence = body;
		return this;
	}

	else_(body: string): this {
		this._alternative = body;
		return this;
	}

	build(): IfStatement {
		return ifStatement({
			condition: this._condition,
			consequence: this._consequence,
			alternative: this._alternative,
			initializer: this._initializer,
		} as IfStatementConfig);
	}

	render(): string {
		return assertValid(renderSilent(this.build()));
	}

	renderSilent(): string {
		return renderSilent(this.build());
	}
}

export function if_(condition: string): IfBuilder {
	return new IfBuilder(condition);
}
