/**
 * Builder for `import_declaration`.
 *
 * Generated by ir-codegen from the go grammar.
 * Do not edit manually — re-run ir-codegen to regenerate.
 */

import type { BuilderTerminal } from '@refactory/grammar-types';
import type { ImportDeclaration, ImportDeclarationConfig } from '../types.ts';
import { renderSilent, assertValid } from '../render.ts';

export function importDeclaration(config: ImportDeclarationConfig): ImportDeclaration {
	return {
		kind: 'import_declaration' as const,
		...config,
	} as ImportDeclaration;
}

class ImportBuilder implements BuilderTerminal<ImportDeclaration> {
	private _children: string;

	constructor(path: string) {
		this._children = path;
	}

	build(): ImportDeclaration {
		return importDeclaration({
			children: this._children,
		} as ImportDeclarationConfig);
	}

	render(): string {
		return assertValid(renderSilent(this.build()));
	}

	renderSilent(): string {
		return renderSilent(this.build());
	}
}

export function import_(path: string): ImportBuilder {
	return new ImportBuilder(path);
}
