/**
 * Builder for `type_declaration`.
 *
 * Generated by ir-codegen from the go grammar.
 * Do not edit manually — re-run ir-codegen to regenerate.
 */

import type { BuilderTerminal } from '@refactory/grammar-types';
import type { TypeDeclaration, TypeDeclarationConfig } from '../types.ts';
import { renderSilent, assertValid } from '../render.ts';

export function typeDeclaration(config: TypeDeclarationConfig): TypeDeclaration {
	return {
		kind: 'type_declaration' as const,
		...config,
	} as TypeDeclaration;
}

class TypeBuilder implements BuilderTerminal<TypeDeclaration> {
	private _children: string;

	constructor(children: string) {
		this._children = children;
	}

	build(): TypeDeclaration {
		return typeDeclaration({
			children: this._children,
		} as TypeDeclarationConfig);
	}

	render(): string {
		return assertValid(renderSilent(this.build()));
	}

	renderSilent(): string {
		return renderSilent(this.build());
	}
}

export function type_(declaration: string): TypeBuilder {
	return new TypeBuilder(declaration);
}
